/*
  # Add short_description column to bills table

  1. Modified Tables
    - `bills`
      - `short_description` (text, nullable) — a short, plain-English,
        one-sentence description of what the bill does, distinct from the
        four-part `summary` field. Generated by the generate-bill-summary
        skill's Step 7.5; used by `BillCard.tsx` as the preferred feed
        preview text over the mechanically-truncated `summary` derivation.

  2. Notes
    - Nullable; existing bills are unaffected and keep rendering their
      existing derived-from-summary preview until backfilled.
    - No RLS policy changes — same read/write policies as every other
      bills column.
    - Uses IF NOT EXISTS to be safe if the column already exists.
    - `my_bill_feed` (20260815120000_add_my_bill_feed_view_and_topic_backfill.sql)
      selects `b.*`, which Postgres expands into an explicit column list at
      CREATE VIEW time — a base-table column added afterward via ALTER TABLE
      does not automatically appear in the view's output. This migration
      re-runs that view's exact definition so `b.*` re-expands to include
      `short_description`. Since the ALTER TABLE below runs first, `b.*`
      would place `short_description` ahead of `support_count` in the
      output, which `CREATE OR REPLACE VIEW` rejects (it only allows new
      trailing columns, not a reordering of existing ones) — so the view is
      dropped and recreated fresh instead of replaced in place. Nothing else
      in this schema references `my_bill_feed` (no dependent views/policies),
      so the drop is safe.
*/

ALTER TABLE bills
  ADD COLUMN IF NOT EXISTS short_description text;

-- ─── Recreate my_bill_feed so b.* re-expansion picks up short_description ──
DROP VIEW IF EXISTS my_bill_feed;

CREATE VIEW my_bill_feed AS
SELECT
  b.*,
  COALESCE(tally.support_count, 0)::int AS support_count,
  COALESCE(tally.oppose_count, 0)::int AS oppose_count,
  COALESCE(tally.total_votes, 0)::int AS total_votes,
  CASE WHEN COALESCE(tally.total_votes, 0) > 0
    THEN ROUND(100.0 * tally.support_count / tally.total_votes, 2)
    ELSE -1
  END AS support_pct,
  COALESCE(b.introduced_date::timestamptz, b.created_at) AS effective_sort_date,
  my_vote.vote AS my_vote,
  CASE
    WHEN my_vote.vote IS NULL THEN NULL
    WHEN district_tally.support_count IS NULL THEN NULL
    WHEN district_tally.support_count + district_tally.oppose_count < 2 THEN NULL
    WHEN district_tally.support_count = district_tally.oppose_count THEN NULL
    WHEN district_tally.support_count > district_tally.oppose_count THEN (my_vote.vote = 'support')
    ELSE (my_vote.vote = 'oppose')
  END AS matched_district_majority
FROM bills b
LEFT JOIN bill_vote_tallies tally ON tally.bill_id = b.bill_id
LEFT JOIN user_votes my_vote ON my_vote.bill_id = b.bill_id AND my_vote.user_id = auth.uid()
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE uv.vote = 'support') AS support_count,
    COUNT(*) FILTER (WHERE uv.vote = 'oppose') AS oppose_count
  FROM user_votes uv
  JOIN user_districts my_ud
    ON my_ud.user_id = auth.uid() AND my_ud.legislative_body_id = b.legislative_body_id
  JOIN user_districts voter_ud
    ON voter_ud.user_id = uv.user_id
    AND voter_ud.legislative_body_id = b.legislative_body_id
    AND voter_ud.district_id = my_ud.district_id
  WHERE uv.bill_id = b.bill_id
) district_tally ON true;

GRANT SELECT ON my_bill_feed TO authenticated;
