/*
  # Add short_description column to bills table

  1. Modified Tables
    - `bills`
      - `short_description` (text, nullable) — a short, plain-English,
        one-sentence description of what the bill does, distinct from the
        four-part `summary` field. Generated by the generate-bill-summary
        skill's Step 7.5; used by `BillCard.tsx` as the preferred feed
        preview text over the mechanically-truncated `summary` derivation.

  2. Notes
    - Nullable; existing bills are unaffected and keep rendering their
      existing derived-from-summary preview until backfilled.
    - No RLS policy changes — same read/write policies as every other
      bills column.
    - Uses IF NOT EXISTS to be safe if the column already exists.
*/

ALTER TABLE bills
  ADD COLUMN IF NOT EXISTS short_description text;
